Use thousand separator in regression prints
Example output:

    Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
    +     100,000 assemblies/Mono.Android-Tests.dll
    Error: apkdiff: Assembly size differs more than 1,024 bytes.
    +      90,000 assemblies/Java.Interop-Tests.dll
    Error: apkdiff: Assembly size differs more than 1,024 bytes.
    Summary:
    +     190,000 Assemblies 0.42% (of 45,052,880)
    +           0 Shared libraries 0.00% (of 27,295,472)
    +      70,000 Package size difference 0.09% (of 75,719,259)
    Error: apkdiff: PackageSize differ more than 512 bytes. apk1 size: 75,719,259 bytes, apk2 size: 75,789,259 bytes.
    Error: apkdiff: Size regression occured, 3 test(s) failed.