Add percentage changed based regression check
Adds two new parameters to enable "percentage changed" based regression
testing.  The `--test-apk-percentage-regression` parameter will report
errors if the overall package size changes more than the specified
threshold percentage.  The `--test-content-percentage-regression`
parameter will report an error for every .dll, .so, or .dex file in the
.apk that has a size change that exceeds the specified threshold
percentage.

The following comparison was done against a .NET 6 preview 4 PR build to
test these changes:

    apkdiff --test-apk-percentage-regression=0.25 --test-content-percentage-regression=0.25 --descrease-is-regression BuildReleaseArm64SimpleDotNet.apkdesc com.xamarin.buildreleasearm64-Signed.apk

    Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
    +     111,232 lib/arm64-v8a/libmonosgen-2.0.so
    Error: apkdiff: File 'lib/arm64-v8a/libmonosgen-2.0.so' has changed by 111,232 bytes (3.01 %). This exceeds the threshold of 0.25 %.
    +         118 assemblies/Mono.Android.dll
    +           4 assemblies/System.Runtime.dll
    -           6 assemblies/UnnamedProject.dll
    -          14 assemblies/System.Linq.dll
    -         168 lib/arm64-v8a/libmonodroid.so
    -       1,654 assemblies/System.Private.CoreLib.dll
    Error: apkdiff: File 'assemblies/System.Private.CoreLib.dll' has changed by -1,654 bytes (-0.32 %). This exceeds the threshold of 0.25 %.
    Summary:
    +           0 Other entries 0.00% (of 58,411)
    +           0 Dalvik executables 0.00% (of 316,728)
    -       1,552 Assemblies -0.23% (of 671,690)
    +     111,064 Shared libraries 2.20% (of 5,038,648)
    +      45,056 Package size difference 1.59% (of 2,828,142)
    Error: apkdiff: PackageSize difference 1.59 % exceeds the threshold of 0.25 %. apk1 size: 2,828,142 bytes, apk2 size: 2,873,198 bytes.